package com.example.ui.screens

import android.content.Intent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.layout.widthIn
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.ArrowForward
import androidx.compose.material.icons.filled.AccountBalance
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Share
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.example.ui.components.CategoryIconBadge
import com.example.ui.components.DailySpendingBarChart
import com.example.ui.components.SpendingDonutChart
import com.example.ui.theme.ExpenseRed
import com.example.ui.theme.GoalGold
import com.example.ui.theme.IncomeGreen
import com.example.ui.viewmodel.ExpenseViewModel
import java.util.Locale

@Composable
fun MonthlyReportScreen(
  viewModel: ExpenseViewModel,
  modifier: Modifier = Modifier
) {
  val context = LocalContext.current
  val report by viewModel.monthlyReport.collectAsStateWithLifecycle()
  val currency = report.currencySymbol

  fun shareReport() {
    val reportText = buildString {
      appendLine("📊 Monthly Budget & Expense Report - ${report.monthDisplay}")
      appendLine("---------------------------------------")
      appendLine("💰 Total Income: $currency${String.format(Locale.getDefault(), "%.2f", report.monthlyIncome)}")
      appendLine("🎯 Fixed Savings (Set Aside): $currency${String.format(Locale.getDefault(), "%.2f", report.savingsGoal)}")
      appendLine("🛒 Spendable Budget: $currency${String.format(Locale.getDefault(), "%.2f", report.spendingBudget)}")
      appendLine("💸 Total Spending: $currency${String.format(Locale.getDefault(), "%.2f", report.totalSpent)}")
      appendLine("💵 Remaining for Spendings: $currency${String.format(Locale.getDefault(), "%.2f", report.spendingRemaining)}")
      appendLine("📈 Status: ${if (!report.isOverSpendingBudget) "Within Budget ✅" else "Over Budget ⚠️"}")
      appendLine("---------------------------------------")
      appendLine("Category Spending Breakdown:")
      report.categorySummaries.filter { it.spent > 0 }.forEach { cat ->
        val status = if (cat.isExceeded) " [⚠️ EXCEEDED BY $currency${String.format(Locale.getDefault(), "%.2f", cat.spent - cat.limit)}]" else ""
        appendLine(
          " • ${cat.categoryName}: $currency${String.format(Locale.getDefault(), "%.2f", cat.spent)} / limit $currency${String.format(Locale.getDefault(), "%.2f", cat.limit)} (%.0f%%)%s".format(
            Locale.getDefault(),
            cat.percentageOfTotal,
            status
          )
        )
      }
      appendLine("---------------------------------------")
      appendLine("Generated by Expense Tracker")
    }

    val intent = Intent(Intent.ACTION_SEND).apply {
      type = "text/plain"
      putExtra(Intent.EXTRA_SUBJECT, "Budget Report: ${report.monthDisplay}")
      putExtra(Intent.EXTRA_TEXT, reportText)
    }
    context.startActivity(Intent.createChooser(intent, "Share Budget Report"))
  }

  BoxWithConstraints(
    modifier = modifier
      .fillMaxSize()
      .background(MaterialTheme.colorScheme.background),
    contentAlignment = Alignment.TopCenter
  ) {
    val isCompact = maxWidth < 360.dp
    val horizontalPad = if (isCompact) 12.dp else 16.dp

    LazyColumn(
      modifier = Modifier
        .widthIn(max = 720.dp)
        .fillMaxSize(),
      contentPadding = PaddingValues(
        start = horizontalPad,
        end = horizontalPad,
        top = 12.dp,
        bottom = 88.dp
      ),
      verticalArrangement = Arrangement.spacedBy(14.dp)
    ) {
      // 1. Month Switcher
      item {
        Card(
          shape = RoundedCornerShape(20.dp),
          colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
          elevation = CardDefaults.cardElevation(defaultElevation = 1.dp),
          modifier = Modifier.fillMaxWidth()
        ) {
          Row(
            modifier = Modifier
              .fillMaxWidth()
              .padding(horizontal = 8.dp, vertical = 6.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
          ) {
            IconButton(
              onClick = { viewModel.navigateMonth(-1) },
              modifier = Modifier.testTag("prev_month_button")
            ) {
              Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Previous Month")
            }

            Column(horizontalAlignment = Alignment.CenterHorizontally) {
              Text(
                text = report.monthDisplay,
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
              )
              Text(
                text = if (report.isCurrentCycle) "Current Month" else "Past Month",
                style = MaterialTheme.typography.labelSmall,
                color = if (report.isCurrentCycle) IncomeGreen else MaterialTheme.colorScheme.onSurfaceVariant,
                fontWeight = FontWeight.SemiBold
              )
            }

            IconButton(
              onClick = { viewModel.navigateMonth(1) },
              modifier = Modifier.testTag("next_month_button")
            ) {
              Icon(Icons.AutoMirrored.Filled.ArrowForward, contentDescription = "Next Month")
            }
          }
        }
      }

      // 2. Financial Summary Overview Card
      item {
        Card(
          shape = RoundedCornerShape(24.dp),
          colors = CardDefaults.cardColors(containerColor = Color.Transparent),
          modifier = Modifier.fillMaxWidth()
        ) {
          Box(
            modifier = Modifier
              .fillMaxWidth()
              .background(
                brush = Brush.linearGradient(
                  colors = listOf(
                    MaterialTheme.colorScheme.primary,
                    Color(0xFF0F766E)
                  )
                )
              )
              .padding(if (isCompact) 16.dp else 20.dp)
          ) {
            Column(verticalArrangement = Arrangement.spacedBy(14.dp)) {
              Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
              ) {
                Text(
                  text = "Monthly Financial Snapshot",
                  style = MaterialTheme.typography.titleMedium,
                  color = MaterialTheme.colorScheme.onPrimary,
                  fontWeight = FontWeight.Bold,
                  maxLines = 1,
                  overflow = TextOverflow.Ellipsis,
                  modifier = Modifier.weight(1f)
                )

                IconButton(
                  onClick = { shareReport() },
                  modifier = Modifier
                    .size(36.dp)
                    .clip(CircleShape)
                    .background(MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.2f))
                    .testTag("share_report_button")
                ) {
                  Icon(
                    imageVector = Icons.Default.Share,
                    contentDescription = "Share Report",
                    tint = MaterialTheme.colorScheme.onPrimary,
                    modifier = Modifier.size(18.dp)
                  )
                }
              }

              // 2x2 Financial Metric Grid
              Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(10.dp)
              ) {
                Surface(
                  shape = RoundedCornerShape(16.dp),
                  color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.14f),
                  modifier = Modifier.weight(1f)
                ) {
                  Column(modifier = Modifier.padding(12.dp)) {
                    Text(
                      text = "Spendable Budget",
                      style = MaterialTheme.typography.labelSmall,
                      color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.85f),
                      maxLines = 1,
                      overflow = TextOverflow.Ellipsis
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                      text = String.format(Locale.getDefault(), "%s%.2f", currency, report.spendingBudget),
                      style = if (isCompact) MaterialTheme.typography.titleMedium else MaterialTheme.typography.titleLarge,
                      fontWeight = FontWeight.Bold,
                      color = MaterialTheme.colorScheme.onPrimary,
                      maxLines = 1,
                      overflow = TextOverflow.Ellipsis
                    )
                  }
                }

                Surface(
                  shape = RoundedCornerShape(16.dp),
                  color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.14f),
                  modifier = Modifier.weight(1f)
                ) {
                  Column(modifier = Modifier.padding(12.dp)) {
                    Text(
                      text = "Total Spent",
                      style = MaterialTheme.typography.labelSmall,
                      color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.85f),
                      maxLines = 1,
                      overflow = TextOverflow.Ellipsis
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                      text = String.format(Locale.getDefault(), "%s%.2f", currency, report.totalSpent),
                      style = if (isCompact) MaterialTheme.typography.titleMedium else MaterialTheme.typography.titleLarge,
                      fontWeight = FontWeight.Bold,
                      color = MaterialTheme.colorScheme.onPrimary,
                      maxLines = 1,
                      overflow = TextOverflow.Ellipsis
                    )
                  }
                }
              }

              Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(10.dp)
              ) {
                Surface(
                  shape = RoundedCornerShape(16.dp),
                  color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.14f),
                  modifier = Modifier.weight(1f)
                ) {
                  Column(modifier = Modifier.padding(12.dp)) {
                    Text(
                      text = "Monthly Income",
                      style = MaterialTheme.typography.labelSmall,
                      color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.85f),
                      maxLines = 1,
                      overflow = TextOverflow.Ellipsis
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                      text = String.format(Locale.getDefault(), "%s%.2f", currency, report.monthlyIncome),
                      style = MaterialTheme.typography.titleMedium,
                      fontWeight = FontWeight.Bold,
                      color = MaterialTheme.colorScheme.onPrimary,
                      maxLines = 1,
                      overflow = TextOverflow.Ellipsis
                    )
                  }
                }

                Surface(
                  shape = RoundedCornerShape(16.dp),
                  color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.14f),
                  modifier = Modifier.weight(1f)
                ) {
                  Column(modifier = Modifier.padding(12.dp)) {
                    Text(
                      text = "Savings Set Aside",
                      style = MaterialTheme.typography.labelSmall,
                      color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.85f),
                      maxLines = 1,
                      overflow = TextOverflow.Ellipsis
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                      text = String.format(Locale.getDefault(), "%s%.2f", currency, report.savingsGoal),
                      style = MaterialTheme.typography.titleMedium,
                      fontWeight = FontWeight.Bold,
                      color = GoalGold,
                      maxLines = 1,
                      overflow = TextOverflow.Ellipsis
                    )
                  }
                }
              }

              // Spending Budget Remaining Pill
              Surface(
                shape = RoundedCornerShape(14.dp),
                color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.15f),
                modifier = Modifier.fillMaxWidth()
              ) {
                Row(
                  modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 14.dp, vertical = 10.dp),
                  horizontalArrangement = Arrangement.SpaceBetween,
                  verticalAlignment = Alignment.CenterVertically
                ) {
                  Text(
                    text = if (!report.isOverSpendingBudget) {
                      String.format(
                        Locale.getDefault(),
                        "Remaining: %s%.2f (%.0f%% used)",
                        currency, report.spendingRemaining,
                        report.spendingUsagePercentage * 100
                      )
                    } else {
                      String.format(
                        Locale.getDefault(),
                        "⚠️ Over Budget by %s%.2f",
                        currency, report.totalSpent - report.spendingBudget
                      )
                    },
                    style = MaterialTheme.typography.bodySmall,
                    fontWeight = FontWeight.Bold,
                    color = if (!report.isOverSpendingBudget) Color(0xFFA7F3D0) else Color(0xFFFFD1D1)
                  )
                }
              }
            }
          }
        }
      }

      // 3. Savings Goal Performance Card
      item {
        Card(
          shape = RoundedCornerShape(20.dp),
          colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
          elevation = CardDefaults.cardElevation(defaultElevation = 1.dp),
          modifier = Modifier.fillMaxWidth()
        ) {
          Column(
            modifier = Modifier
              .fillMaxWidth()
              .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp)
          ) {
            Row(
              modifier = Modifier.fillMaxWidth(),
              horizontalArrangement = Arrangement.SpaceBetween,
              verticalAlignment = Alignment.CenterVertically
            ) {
              Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier.weight(1f)
              ) {
                Box(
                  modifier = Modifier
                    .size(38.dp)
                    .clip(CircleShape)
                    .background(GoalGold.copy(alpha = 0.15f)),
                  contentAlignment = Alignment.Center
                ) {
                  Icon(
                    imageVector = Icons.Default.AccountBalance,
                    contentDescription = null,
                    tint = GoalGold,
                    modifier = Modifier.size(20.dp)
                  )
                }
                Spacer(modifier = Modifier.width(10.dp))
                Column {
                  Text(
                    text = "Protected Monthly Savings",
                    style = MaterialTheme.typography.titleSmall,
                    fontWeight = FontWeight.Bold,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                  )
                  Text(
                    text = String.format(
                      Locale.getDefault(),
                      "%s%.0f saved • Separate from spendings",
                      currency, report.savingsGoal
                    ),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                  )
                }
              }

              Spacer(modifier = Modifier.width(8.dp))

              Surface(
                shape = RoundedCornerShape(10.dp),
                color = IncomeGreen.copy(alpha = 0.15f)
              ) {
                Row(
                  modifier = Modifier.padding(horizontal = 8.dp, vertical = 4.dp),
                  verticalAlignment = Alignment.CenterVertically
                ) {
                  Icon(
                    imageVector = Icons.Default.CheckCircle,
                    contentDescription = null,
                    tint = IncomeGreen,
                    modifier = Modifier.size(14.dp)
                  )
                  Spacer(modifier = Modifier.width(4.dp))
                  Text(
                    text = "Saved",
                    style = MaterialTheme.typography.labelSmall,
                    fontWeight = FontWeight.Bold,
                    color = IncomeGreen
                  )
                }
              }
            }
          }
        }
      }

      // 4. Pie Chart - Visual Breakdown of Expenses by Category
      item {
        Card(
          shape = RoundedCornerShape(22.dp),
          colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
          elevation = CardDefaults.cardElevation(defaultElevation = 2.dp),
          modifier = Modifier
            .fillMaxWidth()
            .testTag("report_screen_pie_chart_card")
        ) {
          Column(
            modifier = Modifier
              .fillMaxWidth()
              .padding(18.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
          ) {
            Column(verticalArrangement = Arrangement.spacedBy(2.dp)) {
              Text(
                text = "Where Your Money Is Going",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
              )
              Text(
                text = "Tap any slice or category to inspect its share of ${report.monthDisplay} expenses",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
              )
            }

            SpendingDonutChart(
              categories = report.categorySummaries,
              totalSpent = report.totalSpent,
              currencySymbol = currency
            )
          }
        }
      }

      // 5. Daily Spending Bar Chart
      item {
        Card(
          shape = RoundedCornerShape(20.dp),
          colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
          elevation = CardDefaults.cardElevation(defaultElevation = 1.dp),
          modifier = Modifier.fillMaxWidth()
        ) {
          Column(
            modifier = Modifier
              .fillMaxWidth()
              .padding(16.dp)
          ) {
            DailySpendingBarChart(
              dailyBreakdown = report.dailyBreakdown,
              currencySymbol = currency
            )
          }
        }
      }

      // 6. Category Breakdown Table
      item {
        Text(
          text = "Detailed Category Report",
          style = MaterialTheme.typography.titleMedium,
          fontWeight = FontWeight.Bold
        )
      }

      items(report.categorySummaries.filter { it.spent > 0 || it.limit > 0 }, key = { it.categoryName }) { cat ->
        Card(
          shape = RoundedCornerShape(16.dp),
          colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
          modifier = Modifier.fillMaxWidth()
        ) {
          Row(
            modifier = Modifier
              .fillMaxWidth()
              .padding(14.dp),
            verticalAlignment = Alignment.CenterVertically
          ) {
            CategoryIconBadge(meta = cat.meta, size = 44.dp, iconSize = 22.dp)

            Spacer(modifier = Modifier.width(12.dp))

            Column(modifier = Modifier.weight(1f)) {
              Text(
                text = cat.categoryName,
                style = MaterialTheme.typography.bodyLarge,
                fontWeight = FontWeight.SemiBold,
                maxLines = 1,
                overflow = TextOverflow.Ellipsis
              )
              Text(
                text = String.format(
                  Locale.getDefault(),
                  "Spent %s%.2f / Limit %s%.2f (%.0f%%)",
                  currency, cat.spent, currency, cat.limit,
                  if (cat.limit > 0) (cat.spent / cat.limit * 100).coerceAtLeast(0.0) else 0.0
                ),
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                maxLines = 1,
                overflow = TextOverflow.Ellipsis
              )
            }

            Spacer(modifier = Modifier.width(8.dp))

            if (cat.isExceeded) {
              Surface(
                shape = RoundedCornerShape(8.dp),
                color = ExpenseRed.copy(alpha = 0.15f)
              ) {
                Text(
                  text = "EXCEEDED",
                  style = MaterialTheme.typography.labelSmall,
                  color = ExpenseRed,
                  fontWeight = FontWeight.ExtraBold,
                  modifier = Modifier.padding(horizontal = 6.dp, vertical = 3.dp)
                )
              }
            } else {
              Text(
                text = String.format(Locale.getDefault(), "%s%.2f", currency, cat.spent),
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
              )
            }
          }
        }
      }
    }
  }
}

