package com.example.ui.screens

import android.content.Intent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.ArrowForward
import androidx.compose.material.icons.filled.AccountBalance
import androidx.compose.material.icons.filled.Autorenew
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.RestartAlt
import androidx.compose.material.icons.filled.Share
import androidx.compose.material.icons.filled.TrendingDown
import androidx.compose.material.icons.filled.TrendingUp
import androidx.compose.material.icons.filled.Warning
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.example.ui.components.CategoryIconBadge
import com.example.ui.components.DailySpendingBarChart
import com.example.ui.components.SpendingDonutChart
import com.example.ui.theme.ExpenseRed
import com.example.ui.theme.GoalGold
import com.example.ui.theme.IncomeGreen
import com.example.ui.viewmodel.ExpenseViewModel
import java.util.Locale

@Composable
fun MonthlyReportScreen(
  viewModel: ExpenseViewModel,
  modifier: Modifier = Modifier
) {
  val context = LocalContext.current
  val report by viewModel.monthlyReport.collectAsStateWithLifecycle()
  val currency = report.currencySymbol
  var showResetConfirmDialog by remember { mutableStateOf(false) }

  fun shareReport() {
    val reportText = buildString {
      appendLine("📊 Monthly Budget & Expense Report - ${report.monthDisplay}")
      appendLine("---------------------------------------")
      appendLine("💰 Total Income: $currency${String.format(Locale.getDefault(), "%.2f", report.monthlyIncome)}")
      appendLine("💸 Total Spending: $currency${String.format(Locale.getDefault(), "%.2f", report.totalSpent)}")
      appendLine("🎯 Fixed Savings Goal: $currency${String.format(Locale.getDefault(), "%.2f", report.savingsGoal)}")
      appendLine("💵 Net Savings: $currency${String.format(Locale.getDefault(), "%.2f", report.netSavings)}")
      appendLine("📈 Savings Goal Status: ${if (report.isSavingsGoalMet) "Goal Met! ✅" else "Below Goal ⚠️"}")
      appendLine("---------------------------------------")
      appendLine("Category Spending Breakdown:")
      report.categorySummaries.filter { it.spent > 0 }.forEach { cat ->
        val status = if (cat.isExceeded) " [⚠️ EXCEEDED BY $currency${String.format(Locale.getDefault(), "%.2f", cat.spent - cat.limit)}]" else ""
        appendLine(" • ${cat.categoryName}: $currency${String.format(Locale.getDefault(), "%.2f", cat.spent)} / limit $currency${String.format(Locale.getDefault(), "%.2f", cat.limit)} (%.0f%%)%s".format(Locale.getDefault(), cat.percentageOfTotal, status))
      }
      appendLine("---------------------------------------")
      appendLine("Generated by Expense Tracker")
    }

    val intent = Intent(Intent.ACTION_SEND).apply {
      type = "text/plain"
      putExtra(Intent.EXTRA_SUBJECT, "Budget Report: ${report.monthDisplay}")
      putExtra(Intent.EXTRA_TEXT, reportText)
    }
    context.startActivity(Intent.createChooser(intent, "Share Budget Report"))
  }

  Column(
    modifier = modifier
      .fillMaxSize()
      .background(MaterialTheme.colorScheme.background)
  ) {
    LazyColumn(
      modifier = Modifier.fillMaxSize(),
      contentPadding = PaddingValues(start = 16.dp, end = 16.dp, top = 16.dp, bottom = 88.dp),
      verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
      // 1. Month Switcher
      item {
        Card(
          shape = RoundedCornerShape(20.dp),
          colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
          elevation = CardDefaults.cardElevation(defaultElevation = 1.dp)
        ) {
          Row(
            modifier = Modifier
              .fillMaxWidth()
              .padding(horizontal = 8.dp, vertical = 6.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
          ) {
            IconButton(
              onClick = { viewModel.navigateMonth(-1) },
              modifier = Modifier.testTag("prev_month_button")
            ) {
              Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Previous Month")
            }

            Column(horizontalAlignment = Alignment.CenterHorizontally) {
              Text(
                text = report.monthDisplay,
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
              )
              Text(
                text = if (report.isCurrentCycle) "Active 1-Month Cycle" else "Archived Cycle",
                style = MaterialTheme.typography.labelSmall,
                color = if (report.isCurrentCycle) IncomeGreen else MaterialTheme.colorScheme.onSurfaceVariant,
                fontWeight = FontWeight.SemiBold
              )
            }

            IconButton(
              onClick = { viewModel.navigateMonth(1) },
              modifier = Modifier.testTag("next_month_button")
            ) {
              Icon(Icons.AutoMirrored.Filled.ArrowForward, contentDescription = "Next Month")
            }
          }
        }
      }

      // 1-Month Cycle Status Pill Card
      item {
        Card(
          shape = RoundedCornerShape(16.dp),
          colors = CardDefaults.cardColors(
            containerColor = if (report.isCurrentCycle) MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.45f)
            else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f)
          )
        ) {
          Row(
            modifier = Modifier
              .fillMaxWidth()
              .padding(14.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.SpaceBetween
          ) {
            Row(
              verticalAlignment = Alignment.CenterVertically,
              modifier = Modifier.weight(1f)
            ) {
              Icon(
                imageVector = Icons.Default.Autorenew,
                contentDescription = null,
                tint = MaterialTheme.colorScheme.primary,
                modifier = Modifier.size(20.dp)
              )
              Spacer(modifier = Modifier.width(10.dp))
              Column {
                Text(
                  text = if (report.isCurrentCycle) "1-Month Count Cycle (Day ${report.daysElapsed} of ${report.daysInCycle})"
                  else "Completed Cycle (${report.daysInCycle} days)",
                  style = MaterialTheme.typography.bodyMedium,
                  fontWeight = FontWeight.SemiBold
                )
                Text(
                  text = if (report.isCurrentCycle) "After this month ends, cycle restarts fresh from $0 on ${report.nextCycleResetDate}."
                  else "Calculated for 1-month period. Next month restarted from $0.00.",
                  style = MaterialTheme.typography.bodySmall,
                  color = MaterialTheme.colorScheme.onSurfaceVariant
                )
              }
            }

            if (report.isCurrentCycle && report.totalSpent > 0) {
              Spacer(modifier = Modifier.width(8.dp))
              OutlinedButton(
                onClick = { showResetConfirmDialog = true },
                shape = RoundedCornerShape(10.dp),
                contentPadding = PaddingValues(horizontal = 8.dp, vertical = 4.dp),
                modifier = Modifier.testTag("reset_cycle_button")
              ) {
                Icon(Icons.Default.RestartAlt, contentDescription = null, modifier = Modifier.size(14.dp))
                Spacer(modifier = Modifier.width(4.dp))
                Text("Reset $0", style = MaterialTheme.typography.labelSmall)
              }
            }
          }
        }
      }

      // 2. Financial Summary Overview Card
      item {
        Card(
          shape = RoundedCornerShape(24.dp),
          colors = CardDefaults.cardColors(containerColor = Color.Transparent),
          modifier = Modifier.fillMaxWidth()
        ) {
          Box(
            modifier = Modifier
              .fillMaxWidth()
              .background(
                brush = Brush.linearGradient(
                  colors = listOf(
                    MaterialTheme.colorScheme.primary,
                    Color(0xFF0F766E)
                  )
                )
              )
              .padding(20.dp)
          ) {
            Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
              Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
              ) {
                Text(
                  text = "Monthly Financial Snapshot",
                  style = MaterialTheme.typography.titleMedium,
                  color = MaterialTheme.colorScheme.onPrimary,
                  fontWeight = FontWeight.Bold
                )

                IconButton(
                  onClick = { shareReport() },
                  modifier = Modifier
                    .size(36.dp)
                    .clip(CircleShape)
                    .background(MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.2f))
                    .testTag("share_report_button")
                ) {
                  Icon(
                    imageVector = Icons.Default.Share,
                    contentDescription = "Share Report",
                    tint = MaterialTheme.colorScheme.onPrimary,
                    modifier = Modifier.size(18.dp)
                  )
                }
              }

              // 2x2 Financial Metric Grid
              Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
              ) {
                // Total Spent
                Surface(
                  shape = RoundedCornerShape(16.dp),
                  color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.12f),
                  modifier = Modifier.weight(1f)
                ) {
                  Column(modifier = Modifier.padding(12.dp)) {
                    Text(
                      text = "Total Spent",
                      style = MaterialTheme.typography.labelSmall,
                      color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.8f)
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                      text = String.format(Locale.getDefault(), "%s%.2f", currency, report.totalSpent),
                      style = MaterialTheme.typography.titleLarge,
                      fontWeight = FontWeight.Bold,
                      color = MaterialTheme.colorScheme.onPrimary
                    )
                  }
                }

                // Net Savings
                Surface(
                  shape = RoundedCornerShape(16.dp),
                  color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.12f),
                  modifier = Modifier.weight(1f)
                ) {
                  Column(modifier = Modifier.padding(12.dp)) {
                    Text(
                      text = "Net Saved",
                      style = MaterialTheme.typography.labelSmall,
                      color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.8f)
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                      text = String.format(Locale.getDefault(), "%s%.2f", currency, report.netSavings),
                      style = MaterialTheme.typography.titleLarge,
                      fontWeight = FontWeight.Bold,
                      color = if (report.netSavings >= 0) Color(0xFFA7F3D0) else Color(0xFFFFD1D1)
                    )
                  }
                }
              }

              Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
              ) {
                // Monthly Income
                Surface(
                  shape = RoundedCornerShape(16.dp),
                  color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.12f),
                  modifier = Modifier.weight(1f)
                ) {
                  Column(modifier = Modifier.padding(12.dp)) {
                    Text(
                      text = "Monthly Income",
                      style = MaterialTheme.typography.labelSmall,
                      color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.8f)
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                      text = String.format(Locale.getDefault(), "%s%.2f", currency, report.monthlyIncome),
                      style = MaterialTheme.typography.titleMedium,
                      fontWeight = FontWeight.Bold,
                      color = MaterialTheme.colorScheme.onPrimary
                    )
                  }
                }

                // Fixed Savings Goal Target
                Surface(
                  shape = RoundedCornerShape(16.dp),
                  color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.12f),
                  modifier = Modifier.weight(1f)
                ) {
                  Column(modifier = Modifier.padding(12.dp)) {
                    Text(
                      text = "Savings Target",
                      style = MaterialTheme.typography.labelSmall,
                      color = MaterialTheme.colorScheme.onPrimary.copy(alpha = 0.8f)
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                      text = String.format(Locale.getDefault(), "%s%.2f", currency, report.savingsGoal),
                      style = MaterialTheme.typography.titleMedium,
                      fontWeight = FontWeight.Bold,
                      color = GoalGold
                    )
                  }
                }
              }
            }
          }
        }
      }

      // 3. Savings Goal Performance Card
      item {
        Card(
          shape = RoundedCornerShape(20.dp),
          colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
          elevation = CardDefaults.cardElevation(defaultElevation = 1.dp)
        ) {
          Column(
            modifier = Modifier
              .fillMaxWidth()
              .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp)
          ) {
            Row(
              modifier = Modifier.fillMaxWidth(),
              horizontalArrangement = Arrangement.SpaceBetween,
              verticalAlignment = Alignment.CenterVertically
            ) {
              Row(verticalAlignment = Alignment.CenterVertically) {
                Box(
                  modifier = Modifier
                    .size(36.dp)
                    .clip(CircleShape)
                    .background(GoalGold.copy(alpha = 0.15f)),
                  contentAlignment = Alignment.Center
                ) {
                  Icon(
                    imageVector = Icons.Default.AccountBalance,
                    contentDescription = null,
                    tint = GoalGold,
                    modifier = Modifier.size(20.dp)
                  )
                }
                Spacer(modifier = Modifier.width(10.dp))
                Column {
                  Text(
                    text = "Fixed Savings Goal",
                    style = MaterialTheme.typography.titleSmall,
                    fontWeight = FontWeight.Bold
                  )
                  Text(
                    text = String.format(
                      Locale.getDefault(),
                      "Target: %s%.0f / month",
                      currency, report.savingsGoal
                    ),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                  )
                }
              }

              Surface(
                shape = RoundedCornerShape(10.dp),
                color = if (report.isSavingsGoalMet) IncomeGreen.copy(alpha = 0.15f) else GoalGold.copy(alpha = 0.15f)
              ) {
                Row(
                  modifier = Modifier.padding(horizontal = 8.dp, vertical = 4.dp),
                  verticalAlignment = Alignment.CenterVertically
                ) {
                  Icon(
                    imageVector = if (report.isSavingsGoalMet) Icons.Default.CheckCircle else Icons.Default.TrendingUp,
                    contentDescription = null,
                    tint = if (report.isSavingsGoalMet) IncomeGreen else GoalGold,
                    modifier = Modifier.size(14.dp)
                  )
                  Spacer(modifier = Modifier.width(4.dp))
                  Text(
                    text = if (report.isSavingsGoalMet) "Target Achieved!" else String.format(Locale.getDefault(), "%.0f%% Achieved", (report.netSavings / report.savingsGoal * 100).coerceAtLeast(0.0)),
                    style = MaterialTheme.typography.labelSmall,
                    fontWeight = FontWeight.Bold,
                    color = if (report.isSavingsGoalMet) IncomeGreen else GoalGold
                  )
                }
              }
            }
          }
        }
      }

      // 4. Donut Chart - Category Breakdown
      item {
        Card(
          shape = RoundedCornerShape(20.dp),
          colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
          elevation = CardDefaults.cardElevation(defaultElevation = 1.dp)
        ) {
          Column(
            modifier = Modifier
              .fillMaxWidth()
              .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
          ) {
            Text(
              text = "Spending by Category",
              style = MaterialTheme.typography.titleMedium,
              fontWeight = FontWeight.Bold
            )

            SpendingDonutChart(
              categories = report.categorySummaries,
              totalSpent = report.totalSpent,
              currencySymbol = currency
            )
          }
        }
      }

      // 5. Daily Spending Bar Chart
      item {
        Card(
          shape = RoundedCornerShape(20.dp),
          colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
          elevation = CardDefaults.cardElevation(defaultElevation = 1.dp)
        ) {
          Column(
            modifier = Modifier
              .fillMaxWidth()
              .padding(16.dp)
          ) {
            DailySpendingBarChart(
              dailyBreakdown = report.dailyBreakdown,
              currencySymbol = currency
            )
          }
        }
      }

      // 6. Category Breakdown Table
      item {
        Text(
          text = "Detailed Category Report",
          style = MaterialTheme.typography.titleMedium,
          fontWeight = FontWeight.Bold
        )
      }

      items(report.categorySummaries.filter { it.spent > 0 || it.limit > 0 }, key = { it.categoryName }) { cat ->
        Card(
          shape = RoundedCornerShape(16.dp),
          colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
          modifier = Modifier.fillMaxWidth()
        ) {
          Row(
            modifier = Modifier
              .fillMaxWidth()
              .padding(14.dp),
            verticalAlignment = Alignment.CenterVertically
          ) {
            CategoryIconBadge(meta = cat.meta)

            Spacer(modifier = Modifier.width(12.dp))

            Column(modifier = Modifier.weight(1f)) {
              Text(
                text = cat.categoryName,
                style = MaterialTheme.typography.bodyLarge,
                fontWeight = FontWeight.SemiBold
              )
              Text(
                text = String.format(
                  Locale.getDefault(),
                  "Spent %s%.2f / Limit %s%.2f (%.0f%%)",
                  currency, cat.spent, currency, cat.limit, (cat.spent / cat.limit * 100).coerceAtLeast(0.0)
                ),
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
              )
            }

            if (cat.isExceeded) {
              Surface(
                shape = RoundedCornerShape(8.dp),
                color = ExpenseRed.copy(alpha = 0.15f)
              ) {
                Text(
                  text = "EXCEEDED",
                  style = MaterialTheme.typography.labelSmall,
                  color = ExpenseRed,
                  fontWeight = FontWeight.ExtraBold,
                  modifier = Modifier.padding(horizontal = 6.dp, vertical = 3.dp)
                )
              }
            } else {
              Text(
                text = String.format(Locale.getDefault(), "%s%.2f", currency, cat.spent),
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
              )
            }
          }
        }
      }
    }

    if (showResetConfirmDialog) {
      AlertDialog(
        onDismissRequest = { showResetConfirmDialog = false },
        icon = {
          Icon(
            imageVector = Icons.Default.RestartAlt,
            contentDescription = null,
            tint = ExpenseRed
          )
        },
        title = { Text("Reset Month Cycle to $0?") },
        text = {
          Text("This will clear all logged expenses for ${report.monthDisplay} and restart your monthly count cycle back to $0.00.")
        },
        confirmButton = {
          Button(
            onClick = {
              viewModel.resetCurrentMonthCycle()
              showResetConfirmDialog = false
            },
            colors = ButtonDefaults.buttonColors(containerColor = ExpenseRed)
          ) {
            Text("Reset to $0")
          }
        },
        dismissButton = {
          TextButton(onClick = { showResetConfirmDialog = false }) {
            Text("Cancel")
          }
        }
      )
    }
  }
}
